<?php
namespace dxapp\themes\inspinia;

/**
 * Class FontawesomeAsset
 *
 * @package dxapp\themes\inspinia
 */
class FontawesomeAsset extends BaseAsset
{
   
    public function init()
    {
        if(YII_ENV_PROD){
            $this->css = [
                '//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'
            ];
        }else{
            $this->css = [
                'font-awesome/css/font-awesome.min.css'
            ];
        }
        parent::init(); // TODO: Change the autogenerated stub
    }
}